/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as LayoutDashboardImport } from './routes/_layout-dashboard'
import { Route as IndexImport } from './routes/index'
import { Route as RegisterIndexImport } from './routes/register/index'
import { Route as LayoutDashboardSearchIndexImport } from './routes/_layout-dashboard/search/index'
import { Route as LayoutDashboardHomeIndexImport } from './routes/_layout-dashboard/home/index'

// Create Virtual Routes

const LayoutDashboardProfileIndexLazyImport = createFileRoute(
  '/_layout-dashboard/profile/',
)()
const LayoutDashboardFollowingIndexLazyImport = createFileRoute(
  '/_layout-dashboard/following/',
)()
const LayoutDashboardProfileLikedIndexLazyImport = createFileRoute(
  '/_layout-dashboard/profile/liked/',
)()

// Create/Update Routes

const LayoutDashboardRoute = LayoutDashboardImport.update({
  id: '/_layout-dashboard',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const RegisterIndexRoute = RegisterIndexImport.update({
  path: '/register/',
  getParentRoute: () => rootRoute,
} as any)

const LayoutDashboardProfileIndexLazyRoute =
  LayoutDashboardProfileIndexLazyImport.update({
    path: '/profile/',
    getParentRoute: () => LayoutDashboardRoute,
  } as any).lazy(() =>
    import('./routes/_layout-dashboard/profile/index.lazy').then(
      (d) => d.Route,
    ),
  )

const LayoutDashboardFollowingIndexLazyRoute =
  LayoutDashboardFollowingIndexLazyImport.update({
    path: '/following/',
    getParentRoute: () => LayoutDashboardRoute,
  } as any).lazy(() =>
    import('./routes/_layout-dashboard/following/index.lazy').then(
      (d) => d.Route,
    ),
  )

const LayoutDashboardSearchIndexRoute = LayoutDashboardSearchIndexImport.update(
  {
    path: '/search/',
    getParentRoute: () => LayoutDashboardRoute,
  } as any,
)

const LayoutDashboardHomeIndexRoute = LayoutDashboardHomeIndexImport.update({
  path: '/home/',
  getParentRoute: () => LayoutDashboardRoute,
} as any)

const LayoutDashboardProfileLikedIndexLazyRoute =
  LayoutDashboardProfileLikedIndexLazyImport.update({
    path: '/profile/liked/',
    getParentRoute: () => LayoutDashboardRoute,
  } as any).lazy(() =>
    import('./routes/_layout-dashboard/profile/liked/index.lazy').then(
      (d) => d.Route,
    ),
  )

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/_layout-dashboard': {
      preLoaderRoute: typeof LayoutDashboardImport
      parentRoute: typeof rootRoute
    }
    '/register/': {
      preLoaderRoute: typeof RegisterIndexImport
      parentRoute: typeof rootRoute
    }
    '/_layout-dashboard/home/': {
      preLoaderRoute: typeof LayoutDashboardHomeIndexImport
      parentRoute: typeof LayoutDashboardImport
    }
    '/_layout-dashboard/search/': {
      preLoaderRoute: typeof LayoutDashboardSearchIndexImport
      parentRoute: typeof LayoutDashboardImport
    }
    '/_layout-dashboard/following/': {
      preLoaderRoute: typeof LayoutDashboardFollowingIndexLazyImport
      parentRoute: typeof LayoutDashboardImport
    }
    '/_layout-dashboard/profile/': {
      preLoaderRoute: typeof LayoutDashboardProfileIndexLazyImport
      parentRoute: typeof LayoutDashboardImport
    }
    '/_layout-dashboard/profile/liked/': {
      preLoaderRoute: typeof LayoutDashboardProfileLikedIndexLazyImport
      parentRoute: typeof LayoutDashboardImport
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren([
  IndexRoute,
  LayoutDashboardRoute.addChildren([
    LayoutDashboardHomeIndexRoute,
    LayoutDashboardSearchIndexRoute,
    LayoutDashboardFollowingIndexLazyRoute,
    LayoutDashboardProfileIndexLazyRoute,
    LayoutDashboardProfileLikedIndexLazyRoute,
  ]),
  RegisterIndexRoute,
])

/* prettier-ignore-end */
